name: qbittorrent
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-Europe/Zagreb}
      WEBUI_PORT: 8080
    ports:
      - "8181:8080"
      - "6881:6881/tcp"
      - "6881:6881/udp"
    volumes:
      - /srv/appdata/qbittorrent:/config
      - /mnt/media:/downloads
