name: plex
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-Europe/Zagreb}
      VERSION: docker
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /srv/appdata/plex:/config
      - /mnt/media/movies:/movies
      - /mnt/media/tv:/tv
